apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: net-test-22nov-artifcatory-gitops
  description: This is GitOps manifest for net-test-22nov-artifcatory   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: net-test-22nov-artifcatory
    backstage.io/kubernetes-id: net-test-22nov-artifcatory 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: net-test-22nov-artifcatory   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:net-test-22nov-artifcatory
