apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: net-test-22nov-artifcatory
  janus-idp.io/tekton: net-test-22nov-artifcatory
  backstage.io/kubernetes-id: net-test-22nov-artifcatory
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: net-test-22nov-artifcatory
resources:
- deployment.yaml
- route.yaml
- service.yaml
